sonar.projectKey=AuditSonar
sonar.projectName=AuditSonar
sonar.sourceEncoding=UTF-8

sonar.sources=front/src,back/src/main
sonar.tests=front/src,back/src/test

sonar.exclusions=**/*.spec.ts,**/*.cy.ts,**/node_modules/**,**/dist/**,**/target/**,**/coverage/**
sonar.test.inclusions=**/*.spec.ts,**/*Test.java,**/*Tests.java,**/*IT.java

sonar.javascript.lcov.reportPaths=front/coverage/front/lcov.info
sonar.coverage.jacoco.xmlReportPaths=back/target/site/jacoco/jacoco.xml
