spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  cors:
    allowed-origin-patterns: ${APP_CORS_ALLOWED_ORIGIN_PATTERNS}
